### ISSUE TITLE
OOP approach

### ISSUE THREAD

**Issue by svkpro** [VKrukovich/TMDB_PHP_API#2]
You don't use OOP approach to make the API requests. 

`<?php
$cm = curl_init();
curl_setopt($cm, CURLOPT_URL, "http://api.themoviedb.org/3/movie/".$id_movie."?api_key=" . $apikey."&language=ru&region=ru");
curl_setopt($cm, CURLOPT_RETURNTRANSFER, TRUE);
curl_setopt($cm, CURLOPT_HEADER, FALSE);
curl_setopt($cm, CURLOPT_HTTPHEADER, array("Accept: application/json"));
$response7 = curl_exec($cm);
curl_close($cm);
$movie_id = json_decode($response7);`

function renderPhpFile($filename, $vars = null) {
  if (is_array($vars) && !empty($vars)) {
    extract($vars);
  }
  ob_start();
  include $filename;
  return ob_get_clean();
}

**Comment by VKrukovich** [comment]
what is wrong with function renderPhpFile?
